### ISSUE TITLE
jCarousel is merged with pikachoose file.

### ISSUE THREAD

**Issue by toutpt** [jeremyfry/PikaChoose#11]
This is bad because I can't update or downgrade version of JCarousel in project wihtout modify the pikachoose file.

In 4.0.4 it was not the case, I don't understand why now in 4.4.4 you have merged both. You should let integrators do their merge.

Could you please revert this change and keep pikachoose in separated file ?

**Comment by jeremyfry** [comment]
Because I have options to enable the carousel baked into PikaChoose I need to make sure that jCarousel is included. I do however keep it listed at the top of the file so I can be easily upgraded, unfortunately you will have to edit the file. 

In the end I believe the ease of use for the average user outweighs the idea of having two files.

**Comment by toutpt** [comment]
You guess a web developer who can add one javascript file can't understand dependencies ? And pikachoose need jquery, so you don't have just one file but two. I'm not sure this is more simple, just a getting started (quite hard to find on the website) should be enough. 

check others: http://galleria.io for example.

Asking to advanced user to modify the file is anti distribution purpose. I'm integrator and I'm used to package external javascripts for the CMS Plone. I don't understand your choice because no other libraries are doing so.

I have opened that bug because I believe this is wrong and it do not make thing easier. If you have dependency provide it in the release, the documentation, and let integrator do the rest (merging, ...)

By the way pikachoose is just a great jquery addon.

**Comment by jeremyfry** [comment]
I expect developers to be able to understand dependicies, but the fact of the matter is that many of the people using jQuery plugins are not developers. Generally when I pickup a designer client that needs help I spend time removing 5 different jQuery includes because every guide said 'include these files'. 

Your points are certainly valid, but at the end of the day I made PikaChoose easy for the person who shouldn't be using it to hopefully get right (a direct request from a designer who couldn't figure out Galleria). 

I'll take it into consideration, but at this time I'm going to try and keep it easiest for those out there who are not developers. Also thanks for the heads up on the getting started, didn't realize it got buried when I move to the new design.
